### ISSUE TITLE
Images unavailable in HTML output 

### ISSUE THREAD

**Issue by edmund-davis** [microsoft/Microsoft365DSC#1070] opened 2021-02-23 18:07 UTC
#### Details of the scenario you tried and the problem that is occurring
Generating a report from a DSC script in HTML references image URIs which do not appear to exist.  For example:
src="http://microsoft365dsc.com/Images/AzureAD.jpg"

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by ararag** [comment] 2021-02-23 21:51
This might have something to do with the ongoing certificate issue. Even though the links are http links they seem to be redirected to https. I'd imagine the certificate problem might cause the browser refusing to load the images from the https-source when the certificate isn't valid. I believe the problem should be resolved when the certificate issue gets corrected.

**Comment by desmay** [comment] 2021-02-24 13:21
This should be resolved now that certificate is renewed

**Comment by ykuijs** [comment] 2021-02-25 11:30
This was indeed caused by the SSL issue, which was solved yesterday. Closing this issue now. Please reopen if the issue still occurs.

**Closed by ykuijs** 2021-02-25 11:30 UTC
