### ISSUE TITLE
Microsoft365DSC: Issue Compiling MOF - ResourceModuleTuplesToImport error

### ISSUE THREAD

**Issue by RedMageKnight** [microsoft/Microsoft365DSC#1898] opened 2022-04-21 22:52 UTC
#### Details of the scenario you tried and the problem that is occurring
I was just trying to simply run the PS1 file to generate the MOF file and received the error and could continue no further.

#### Verbose logs showing the problem
``Configuration: Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".``
#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
There's a lot of info to go through to obfuscate the file - if needed I will provide. Just for context, I ran a "Full" configuration pull on the source tenant.

#### The operating system the target node is running
`OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
OsLanguage           : en-US
OsMuiLanguages       : {en-US}`

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.420.1

**Comment by andikrueger** [comment] 2022-05-06 07:41
Any chance you could narrow it down? Uncomment a few resources within the config, compile and apply this one. Would be great if we find the resource that causes the issue.

**Comment by andikrueger** [comment] 2022-05-31 08:20
Will close this issue in regards to to the related issues #1699 and #1782

**Comment by ykuijs** [comment] 2023-02-27 08:28
**SOLUTION:**
Ran into this issue as well. Did some investigation and found that if you install the PSDesiredStateConfiguration module, the issue is resolved. Apparently v1.0 of this module is installed by default, which is causing this issue. The PSGallery has v2.0.6 and after installing that, all works as expected.

**Closed** 2023-02-27 15:23 UTC
