### ISSUE TITLE
Cannot update TeamsMessagingPolicy using Set-TargetResource

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1978] opened 2022-05-31 12:23 UTC
#### Details of the scenario you tried and the problem that is occurring
I am trying to update the Global TeamsMessagingPolicy. Intention is to set AllowUserTranslation from True to False.

#### Verbose logs showing the problem
Nothing actually happens. Using PS to update the settings works w/o any issues.
#### Suggested solution to the issue
I haven't been able to track down the root cause just yet. It seems that we aren't entering any option of the if-elseif-elseif construct in https://github.com/microsoft/Microsoft365DSC/blob/6edc849b7500dcd9316d188755b42a164800adc2/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMessagingPolicy/MSFT_TeamsMessagingPolicy.psm1#L302
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
MSFT_TeamsMessagingPolicy Global	AllowUserTranslation	True	False

**Comment by SebastianGoers** [comment] 2022-05-31 13:51
Removing -force:$True in https://github.com/microsoft/Microsoft365DSC/blob/6edc849b7500dcd9316d188755b42a164800adc2/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMessagingPolicy/MSFT_TeamsMessagingPolicy.psm1#L308 seems to solve the issue.

**Comment by SebastianGoers** [comment] 2022-06-03 08:11
I'm no longer able to reproduce the issue with the current release.

**Comment by andikrueger** [comment] 2022-06-03 08:41
I'll close this issue for now. Thanks for the update.

**Comment by SebastianGoers** [comment] 2022-06-09 09:55
@andikrueger  I am afraid I need to revoke my statement. Apparently the issue still persists.; changes are not being reflected on the tenant. Kindly reopen the issue.

**Comment by andikrueger** [comment] 2022-06-09 09:56
Looks like we need to implement the suggested change.

**Comment by SebastianGoers** [comment] 2022-06-09 10:10
I have a similar beaviour in TeamsCallingPolicy but I don't know why just yet.

**Comment by goorallab** [comment] 2022-06-16 11:44
Hello, 

I can confirm that this bug still exist in version `1.22.525.1` of the product. 

Fix suggested by @SebastianGoers if resolves the issue as cmdlets:
- `New-CsTeamsMessagingPolicy`
- `Set-CsTeamsMessagingPolicy`
- `Remove-CsTeamsMessagingPolicy`
don't have `-Force` parameter in in `MicrosoftTeams` version of module:
![image](https://user-images.githubusercontent.com/41610384/174062132-1340f29d-3ddd-4a97-9359-b6e667c583f9.png)

That parameter exists however in `SkypeForBusiness` module as seen in [documentation](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmessagingpolicy?view=skype-ps) so I assume that's where confusion comes from.

Hoping for the fix in next release!

**Comment by desmay** [comment] 2022-06-16 14:53
I'll work to get this updated for next release

**Comment by NikCharlebois** [comment] 2022-07-22 20:24
This has been fixed in a previous release.

**Closed by NikCharlebois** 2022-07-22 20:24 UTC
Labels: Bug, Teams
