### ISSUE TITLE
TeamsMeetingPolicy: NewMeetingRecordingExpirationDays does not allow "-1"

### ISSUE THREAD

**Issue by heizkoerperchen** [microsoft/Microsoft365DSC#3889] opened 2023-11-14 09:19 UTC
### Description of the issue

As documentation is stating 
![image](https://github.com/microsoft/Microsoft365DSC/assets/97455455/a14dbda1-1370-454a-8e57-e0d2b2bf10c8)

and also an actual export is containing, it's possible to set the value for the parameter NewMeetingRecordingExpirationDays in TeamsMeetingPolicies to "-1" which means "never". 
Unfortunately the data type for this parameter within Microsoft365DSC is set to UInt32 which only can contain values between 0 and 4294967295. This is leading to an error that "-1" is not in the range of UInt32.

### Microsoft 365 DSC Version

V1.23.1108.1

### Which workloads are affected

Teams

**Comment by malauter** [comment] 2023-12-27 13:21
Duplicate of #4090 
Will be fixed with #4093

**Closed by malauter** 2023-12-27 13:21 UTC
Labels: Bug, Teams, V1.23.1108.1
