### ISSUE TITLE
Export Custom Configuration Profile with XML file

### ISSUE THREAD

**Issue by Ruthhl3ss** [microsoft/Microsoft365DSC#4201] opened 2024-01-20 08:14 UTC
### Description of the issue

I would like to export a Custom configuration profile within Intune. This profile contains an XML for taskbarpinned items.

This is the error I get:

[2024/01/20 09:04:38]
{NotSpecified}
System.Management.Automation.MethodInvocationException: Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex" ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CallSite.Target(Closure , CallSite , String , String , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Convert-DSCStringParamToVariable(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Convert-DSCStringParamToVariable, C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\2.0.0.18\ReverseDSC.Core.psm1: line 766
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\DSCResources\MSFT_IntuneDeviceConfigurationCustomPolicyWindows10\MSFT_IntuneDeviceConfigurationCustomPolicyWindows10.psm1: line 626
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\modules\M365DSCReverse.psm1: line 639
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\modules\M365DSCUtil.psm1: line 1312
at <ScriptBlock>, <No file>: line 1
TenantId: 7l4l1k.onmicrosoft.com

This is the JSON file representing the policy:

{
  "@odata.context": "https://graph.microsoft.com/beta/$metadata#deviceManagement/deviceConfigurations/$entity",
  "@odata.type": "#microsoft.graph.windows10CustomConfiguration",
  "id": "e29a1e36-5040-4c4a-b4bb-40228d626a5b",
  "lastModifiedDateTime": "2023-09-18T09:01:45.2510971Z",
  "roleScopeTagIds": [
    "0"
  ],
  "supportsScopeTags": true,
  "deviceManagementApplicabilityRuleOsEdition": null,
  "deviceManagementApplicabilityRuleOsVersion": null,
  "deviceManagementApplicabilityRuleDeviceMode": null,
  "createdDateTime": "2023-09-18T09:01:45.2510971Z",
  "description": null,
  "displayName": "BL-WIN-CUSTOM-TaskbarLayout-V1.0",
  "version": 1,
  "omaSettings": [
    {
      "@odata.type": "#microsoft.graph.omaSettingStringXml",
      "displayName": "TaskbarLayout",
      "description": null,
      "omaUri": "./User/Vendor/MSFT/Policy/Config/Start/StartLayout",
      "secretReferenceValueId": "e72752df-fdc2-4441-9fc6-74ec341b44fb_e29a1e36-5040-4c4a-b4bb-40228d626a5b_0c24ce6b-a164-4235-a540-59262c68a8dd",
      "isEncrypted": true,
      "fileName": "TaskBarPinnedItems.xml",
      "value": "XML FILE"
    }
  ]
}

### Microsoft 365 DSC Version

1.24.117.1

### Which workloads are affected

other

### The DSC configuration

```powershell
The DSC configuration can't be created
```

### Verbose logs showing the problem

```powershell
[2024/01/20 09:04:38]
{NotSpecified}
System.Management.Automation.MethodInvocationException: Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex" ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CallSite.Target(Closure , CallSite , String , String , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Convert-DSCStringParamToVariable(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Convert-DSCStringParamToVariable, C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\2.0.0.18\ReverseDSC.Core.psm1: line 766
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\DSCResources\MSFT_IntuneDeviceConfigurationCustomPolicyWindows10\MSFT_IntuneDeviceConfigurationCustomPolicyWindows10.psm1: line 626
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\modules\M365DSCReverse.psm1: line 639
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\modules\M365DSCUtil.psm1: line 1312
at <ScriptBlock>, <No file>: line 1
TenantId: 7l4l1k.onmicrosoft.com
```

### Environment Information + PowerShell Version

```powershell
$PSVersionTable


OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.22621.2506
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.22621.2506
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by ricmestre** [comment] 2024-01-20 11:57
This a duplicate of #4174

**Comment by Ruthhl3ss** [comment] 2024-01-20 11:59
Allright, we can close this one.

**Closed** 2024-03-22 12:59 UTC
