### ISSUE TITLE
SPOSharingSettings not in desired state output false but the settings where correctly applied/configured in a tenant

### ISSUE THREAD

**Issue by atdheekurteshi** [microsoft/Microsoft365DSC#2182] opened 2022-08-05 13:07 UTC
**Details of the scenario you tried and the problem that is occurring**

**SPOSharingSettings** below settings are correctly applied/configured in our tenant but I don't understand why are they **'NotInDesiredState'**.
 
When I run the following commands in the **Power-Shell** everything seems to be working fine for **SPOSharingSettings**:
```
Publish-DscConfiguration -Path C:\...\MOFs\MainConfig -Force
Start-DscConfiguration -UseExisting -Force -Verbose -Wait
$res=Test-DscConfiguration -ComputerName localhost -Detailed -Verbose
```

but the following **Power-Shell** command 
```
PS C:\Windows\system32> $res.ResourcesNotInDesiredState

ConfigurationName     : MainConfig
DependsOn             :
ModuleName            : Microsoft365DSC
ModuleVersion         : 1.22.720.1
PsDscRunAsCredential  :
ResourceId            : [SPOSharingSettings]Container-46-b7272ff0-e466-48ce-9d15-9fe57a4412f3
SourceInfo            : ::433::3::SPOSharingSettings
DurationInSeconds     : 3.453
Error                 :
FinalState            :
InDesiredState        : False
InitialState          :
InstanceName          : Container-46-b7272ff0-e466-48ce-9d15-9fe57a4412f3
RebootRequested       : False
ResourceName          : SPOSharingSettings
StartDate             : 8/5/2022 11:37:08 AM
StateChanged          : False
PSComputerName        : localhost
CimClass              : root/Microsoft/Windows/DesiredStateConfiguration:MSFT_ResourceNotInDesiredState
CimInstanceProperties : {ConfigurationName, DependsOn, ModuleName, ModuleVersion...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties


PS C:\Windows\system32> $res.ResourcesNotInDesiredState | select ResourceId

ResourceId
----------
[SPOSharingSettings]Container-46-b7272ff0-e466-48ce-9d15-9fe57a4412f3

```
outputs the **SPOSharingSettings** not in desired state 

**The DSC configuration that is used to reproduce the issue (as detailed as possible)**

MOF file extract:

```
/*
@TargetNode='localhost'
@GeneratedBy=xxx
@GenerationDate=
@GenerationHost=xxx
*/

instance of MSFT_SPOSharingSettings as $MSFT_SPOSharingSettings1ref
{
 SharingCapability = "Disabled";
 TenantId = "";
 Ensure = "Present";
 PreventExternalUsersFromResharing = True;
 RequireAcceptingAccountMatchInvitedAccount = True;
 ResourceID = "[SPOSharingSettings]Container-46-c3ac0965-e39f-4cde-a750-d7b6923450b4";
 DefaultLinkPermission = "Edit";
 IsSingleInstance = "Yes";
 SourceInfo = "::402::3::SPOSharingSettings";
 CertificateThumbprint = "";
 ApplicationId = "";
 ModuleVersion = "1.22.720.1";
 ModuleName = "Microsoft365DSC";
 DefaultSharingLinkType = "Direct";

 ConfigurationName = "MainConfig";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";
 

                        MinimumCompatibleVersion = "1.0.0";
 

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 

                        Author="";
 

                        GenerationDate="";
 

                        GenerationHost="xxx";


                        ContentType="PasswordEncrypted";
 

                        Name="MainConfig";


                    };
```
```
#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}

-->

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.720.1
```

**Comment by andikrueger** [comment] 2022-08-08 07:04
Could you share the verbose log of the Test-DSCConfiguration or the Event Log items? Within the Windows Event Log there should be a full overview of which settings are marked as drifted.

**Comment by andikrueger** [comment] 2022-08-08 08:41
Thanks for the feedback. Your configuration did not specify the Parameter "Ensure". Therefor the default value was used. Which is present.
This is kind of a bug, as the Test-Configuration obviously compares the Ensure Property and does not include the default value for that.

**Comment by andikrueger** [comment] 2022-08-12 08:13
Thanks for the update. Actually, I think I found the cause of this issue. The Get-Method does not return the Ensure Parameter. Therefor the compare function fails for this one:

https://github.com/microsoft/Microsoft365DSC/blob/17984cf89f4c13c591e1b935564e060f2be81273/Modules/Microsoft365DSC/DSCResources/MSFT_SPOSharingSettings/MSFT_SPOSharingSettings.psm1#L184-L214

**Closed** 2022-08-25 16:31 UTC
Labels: Bug, SharePoint Online
