### ISSUE TITLE
New-M365DSCDeltaReport list identical resources as configured differently

### ISSUE THREAD

**Issue by magnusatteamsrocks** [microsoft/Microsoft365DSC#1811] opened 2022-03-09 12:15 UTC
New-M365DSCDeltaReport will list identical resources as configured differently in the report if a value in the .ps1 files is either "" or @().
Tested with dscparser 1.3.0.2, 1.3.0.3.

Example:

Source:
AADGroupsNamingPolicy 42c01b2f-1316-4cdd-a43d-a26905fdf2bb
        {
            Credential                    = $Credscredential;
            CustomBlockedWordsList        = @();
            Ensure                        = "Present";
            IsSingleInstance              = "Yes";
            PrefixSuffixNamingRequirement = "";
        }

**Comment by andikrueger** [comment] 2022-03-11 08:31
Maybe this issue is related to #1815.

Would you be able to share two configurations so that we can try to reproduce the issue?

**Comment by MattBrowne1** [comment] 2022-03-14 11:12
@andikrueger I am seeing this also, with version '1.22.216.1', and version '1.3.0.2' of DSCParser.

I'm running the following export twice without making any changes to the config etc, so the output files should be identical...
Export-M365DSCConfiguration -Workloads TEAMS  -Credential $Credential -Path $path -FileName $fileName

If I use the TeamsVoiceRoutingPolicy as an example, the outputted DSC files contains this....
        TeamsVoiceRoutingPolicy c1f0c0cc-de23-4fc3-8e1f-716b31abd977
        {
            Credential           = $Credscredential;
            Ensure               = "Present";
            Identity             = "Global";
            OnlinePstnUsages     = @();
        }
 
Notice the "OnlinePstnUsages     = @();" line.  This is what I would expect because this setting isn't specified in our config.

Then if I run the Delta report....
New-M365DSCDeltaReport -Source .\file1.ps1 -Destination .\file2.ps1 -OutputPath .\DeltaOutput.html

The output report shows this.....
![image](https://user-images.githubusercontent.com/26323872/158160034-7e3f608c-8ac4-4569-abe1-083e30db2580.png)

This is just one example in the report.  There are a bunch of other configuration items that aren't specified, but show up as differences in the report.  I guess it's picking up the blank array '@()' as a difference for some reason.  It would be good to ignore these if they are @() in both source and destination

I happy to give more examples or run tests if needed.

**Comment by krugerd** [comment] 2022-04-05 15:09
I've noticed this issue as well running 1.22.323.1:  I have a source file, and then made a copy of it.  Then when using both identical files running New-M365DSCDeltaReport, I get 78 resources configured differently.  Yet it is the same exact file contents in both the source and destination.  

The source values and destination values in the delta report html appear all identical - all blank.

copy boo.ps1 boo2.ps1
New-M365DSCDeltaReport -source .\boo.ps1 -Destination .\boo2.ps1 -OutputPath C:\ps\dsc\boo-deltatest.html

**Comment by MaciejZZZ** [comment] 2022-04-08 13:05
Hi Guys
I just downgraded from 1.22.323.1 to 1.22.216.1 - because when running New-M365DSCDeltaReport the ResourceIDs were displayed - and now I have the same issue as described in this thread - empty lines :(

**Comment by magnusatteamsrocks** [comment] 2022-04-19 11:40
Yes, I downgraded to 1.21.1124.2 myself to overcome this issue, the delta report has been totally broken for a a while. Anyone doing some investigation on this? I would love to be able to take advantage of some of the later features and the pre v4 MicrosoftTeams PowerShell module deprecation is coming up...

**Comment by ykuijs** [comment] 2022-05-20 14:58
I have fixed this issue and am about to submit a PR. The fix will be included in next weeks release!

**Closed** 2022-05-20 19:53 UTC
Labels: Bug, Core Engine
