### ISSUE TITLE
about M365DSCReportFromConfiguration commandlet

### ISSUE THREAD

**Issue by ytfj** [microsoft/Microsoft365DSC#3342] opened 2023-05-25 00:09 UTC
I checked and found that the BlockUrls parameter in the AtpPolicyForO365 commandlet was removed on 5/17. However, the New-M365DSCReportFromConfiguration commandlet did not detect any difference in value. Is this by design?

**Comment by NikCharlebois** [comment] 2023-06-09 17:29
New-M365DSCReportFromConfiguration does not detect differences, it simply takes the incoming configuration and converts it to another format. The New-M365DSCDeltaReport is what you want to use. If that's what you were referring to, can you please share the two configs you are trying to compare for us to investigate? Thanks

**Comment by yutafuji-ms** [comment] 2023-06-14 23:54
I don't have the config as I am posting on behalf of the customer, but I have confirmed that there are no BlockUrls in the customer's two configs*.
*Export-M365DSCConfiguration -Components @("EXOAtpPolicyForO365") results

Does Export-M365DSCConfiguration exclude any parameters from the cmdlet's output? If there are any criteria for which parameters it does not target, please let me know.

**Comment by yutafuji-ms** [comment] 2023-06-20 15:21
Yes, I am asking about any parameters that are currently exposed by an underlying cmdlet and not handled by the DSC project. I understand the reason for not having the BlockUrls parameter, as it is deprecated. Thank you for the clarification.

**Comment by NikCharlebois** [comment] 2023-06-27 10:47
In theory, the resource should be targeting any parameters that are not deprecated. We try to align with the various product groups, in this case EXO, to align our resources with any changes to the PowerShell modules. If you find that any parameters that are not internal, read-only or deprecated are missing from a resource, please have them reported through issues and we'll make sure to include them in a future release. Thanks

**Comment by andikrueger** [comment] 2023-07-06 21:09
@yutafuji-ms are there any further questions? If not, I would close this issue.

**Comment by yutafuji-ms** [comment] 2023-07-09 23:38
You can go ahead and close this issue. I have no further questions. Thank you.

**Closed** 2023-07-10 04:28 UTC
Labels: Pending Information, Core Engine
