### ISSUE TITLE
Microsof365DSC export MS graph API access token timeouts

### ISSUE THREAD

**Issue by tacummins1** [microsoft/Microsoft365DSC#1668] opened 2022-01-10 16:51 UTC
Exporting the config from a tenant with a large amount of AAD and 365 config will result in graph API call failures by Microsoft365DSC modules after the default 1 hour access token lifetime is breached.

Ideally this could be fixed in the Microsoft365DSC modules by adding logic to refresh the access token just prior to expiry.  As a temporary workaround it is possible for an admin to assign a token lifetime policy to the Microsoft Graph Powershell service principal which increases the access token lifetime prior to running the export.  

Until the issue is addressed in the code, recommend including the workaround in documentation as this may affect a number of AAD tenants.

**Comment by NikCharlebois** [comment] 2022-01-10 18:11
Thanks for reporting this. This would need to be addressed inside the MSCloudLoginAssistant module which is the component that handles all authentication for M365DSC. Will investigate further.

**Comment by andikrueger** [comment] 2022-06-03 07:06
@tacummins1 Is this still an issue with the latest version of M365DSC? There were a few changes of the last couple of months.

**Comment by andikrueger** [comment] 2022-06-20 13:08
Closing due to inactivity. Feel free to reopen this issue, if it is still present.

**Comment by DavidAdamGriffith** [comment] 2022-08-30 20:30
@andikrueger  This issue appears to still be present - running fresh installs against 2 tenants, neither make it very far into the 'Full' workload, as after about an hour the console complains about the token having expired

**Comment by andikrueger** [comment] 2022-08-31 07:51
I did some digging about this issue. 

MSCloudLoginAssistant is used to mange connections to the various workloads. For MS Graph, The Microsoft.Graph.Authentication PS Module is used for establishing connections to MSGraph. Within MSCloudLoginAssistant there are various checks, if there are already established connections for a certain workload. For Graph this line of code causes your timeout issue:

https://github.com/microsoft/MSCloudLoginAssistant/blob/9574b54ef6a81f1abf23b0c1b2a667480de31593/Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1#L29

![image](https://user-images.githubusercontent.com/15608729/187617400-11997a70-a406-41d2-8b8b-6558ceb2b99d.png)

MSCloudLoginAssistant uses the global variables to to save connection information. As your long running operation comes with a open connection, this variable will be set to true. 

`Get-MGContext` is used to determine, if there a Graph context established:

![image](https://user-images.githubusercontent.com/15608729/187617767-19ea97db-3942-4321-a9aa-feb37de25cbc.png)

This context holds information about the authentication context (I:

![image](https://user-images.githubusercontent.com/15608729/187617944-e5394686-e20a-42c4-a39d-c372726b4e84.png)

I was able to get a Graph Context even though the session timed out. At the moment, there is no method to obtain the MSAL token. This token usually expires after one hour. The token lifetime is part of the token.

To have a very more reliable indicator on the connection availability, it would be great to have a method within Microsoft.Graph.Authentication module that would either expose the token (eg. `Get-MgMSALToken`) or the expiry timestamp (e.g. `Get-MgTokenExpiryTimeStamp`) (`exp` part of the token claim).

cc/ @NikCharlebois @peombwa

**Comment by andikrueger** [comment] 2022-08-31 14:02
Just to add another idea:
Within MSCloudLoginAssistant there is a ConnectedDateTime within the MicrosoftGraph.psm1

![image](https://user-images.githubusercontent.com/15608729/187697322-829a7dae-ed76-4446-a853-7bc39bc557c8.png)

This would be a quick fix for this issue, if we add a check to line 28. This check should test, if the ConnectedDateTime is within the last hour.

**Comment by NikCharlebois** [comment] 2022-10-14 18:11
For whatever reason, I am not able to reproduce this behavior. For every instance of a resource, we call back into the New-M365DSCConnection cmdlet which then verifies if the context is still active via Get-MgContext, and if it's not, it re-authenticates automatically. Will close for the moment and re-open if someone can elaborate on exact repro steps.

**Closed by NikCharlebois** 2022-10-14 18:11 UTC
Labels: Bug, Enhancement, Core Engine
