### ISSUE TITLE
Export-M365DSCConfiguration: Dual monitors cause display issues

### ISSUE THREAD

**Issue by KenBenjamin** [microsoft/Microsoft365DSC#1068] opened 2021-02-23 16:21 UTC
#### Details of the scenario you tried and the problem that is occurring
If you have a dual-monitor setup, the GUI sizes based on the secondary display (in my case oriented in portrait) but displays on the primary display (in my case in landscape). When these monitors are not the same resolution or size, the primary display may not show all the content. Moving the window to the secondary display does not resolve the problem.

#### Suggested solution to the issue
Temporary work-around is to disable the secondary display but it would be better if the application correctly detected the primary display or, best of all, resized to fit the current display.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2004
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.217.1

**Comment by ykuijs** [comment] 2021-02-25 11:35
This is caused by the same issue as mentioned in issue #1069:

Unfortunately this is correct. The UI is created using PowerShell code, which means we cannot use any GUI editor. That makes developing a proper UI really difficult. Right now the only workaround is to switch back one display.

We are looking at a ways to solve this issue.

**Comment by NikCharlebois** [comment] 2021-07-19 18:19
M365DSC's GUI will be moving to a web based version over the next few weeks. This will address this issue.

**Closed by NikCharlebois** 2021-07-19 18:19 UTC
Labels: Core Engine, Enhancement
