### ISSUE TITLE
IntuneEndpointDetectionAndResponsePolicyWindows10: configurationtype_onboarding_fromconnector does not match with the list

### ISSUE THREAD

**Issue by CovidtheDog2024** [microsoft/Microsoft365DSC#5300] opened 2024-10-30 00:40 UTC
### Description of the issue

Good day!

Two issues encounter for this Intune resource. 
Workload: Intune
Resource: IntuneEndpointDetectionAndResponsePolicyWindows10

1.  Error during import if the configuration type is "AutoFromConnector" but no error if the configuration type is "onboard" (refer to the logs below)
2.  Duplicate/create a new policy instead of an update if re-run the resource. (Refer to the image below )

![Image](https://github.com/user-attachments/assets/97409efe-51d8-4fb9-a8a0-149e7e47b506)

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Intune

### The DSC configuration

Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.24.1016.1'

    Node localhost
    {
        IntuneEndpointDetectionAndResponsePolicyWindows10 "IntuneEndpointDetectionAndResponsePolicyWindows10-test1"
        {
            Assignments          = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    groupDisplayName = 'IntuneUsers'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = '40855b83-24ad-xxxx-xxxx-xxxxxxxxxx'
                }
            );
            ConfigurationType    = "AutoFromConnector";
            Credential           = $Credscredential;
            configurationBlob    = @"
                                   {"body":"{\"previousOrgIds\":[],\"orgId\":\"027ce7f5-0237-4fe5-a7dd-fb2ff3ceb14f\",\"geoLocationUrl\"}
"@                                
            Description          = "";
            DisplayName          = "test1";
            Ensure               = "Present";
            Identity             = "3d737b8f-b58e-4b64-a97b-xxxxxxxxxxxxxxxx";
            RoleScopeTagIds      = @("0");
            SampleSharing        = "1";
        }
    }
}

### Verbose logs showing the problem

VERBOSE: [MyVM]:                            [[IntuneEndpointDetectionAndResponsePolicyWindows10]IntuneEndpointDetectionAndResponsePolicyWindows10-test1] Could not find an Intu
ne Endpoint Detection And Response Policy for Windows10 with Id {3d737b8f-b58e-4b64-a97b-080757581d1d}
VERBOSE: [MyVM]:                            [[IntuneEndpointDetectionAndResponsePolicyWindows10]IntuneEndpointDetectionAndResponsePolicyWindows10-test1] Could not find an Intu
ne Endpoint Detection And Response Policy for Windows10 with Name {test1}.
VERBOSE: [MyVM]:                            [[IntuneEndpointDetectionAndResponsePolicyWindows10]IntuneEndpointDetectionAndResponsePolicyWindows10-test1] Creating an Intune End
point Protection And Response Policy for Windows10 with Name {test1}
[BadRequest] : {
  "_version": 3,
  "Message": "device_vendor_msft_windowsadvancedthreatprotection_configurationtype:  Selected Option 
device_vendor_msft_windowsadvancedthreatprotection_configurationtype_onboarding_fromconnector does not match with the list of expected options: device_vendor_msft_windowsadvancedthreatp
rotection_configurationtype_autofromconnector,device_vendor_msft_windowsadvancedthreatprotection_configurationtype_onboard,device_vendor_msft_windowsadvancedthreatprotection_configurati
ontype_offboard. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 2b462795-4932-4adf-b0b6-b8f1c74325fb - Url: 
https://fef.msuc02.manage.microsoft.com/DeviceConfigV2/DCV2GraphService/de147310-ffff-2353-0608-102813403780/deviceManagement/configurationPolicies?api-version=5024-09-01",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
    + CategoryInfo          : InvalidOperation: ({ Headers = , b...urationPolicy }:) [], CimException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.Beta.PowerShell.Cmdlets.NewMgBetaDeviceManagementConfigurationPolicy_Create
    + PSComputerName        : localhost
 
VERBOSE: [MyVM]: LCM:  [ End    Set      ]  [[IntuneEndpointDetectionAndResponsePolicyWindows10]IntuneEndpointDetectionAndResponsePolicyWindows10-test1]  in 3.6000 seconds.
The PowerShell DSC resource '[IntuneEndpointDetectionAndResponsePolicyWindows10]IntuneEndpointDetectionAndResponsePolicyWindows10-test1' with SourceInfo 
'C:\newDSC\IntuneEndpointDetectionAndResponsePolicyWindows10\M365TenantConfig.ps1::34::9::IntuneEndpointDetectionAndResponsePolicyWindows10' threw one or more non-terminating errors 
while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [MyVM]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

### Environment Information + PowerShell Version

OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.22621.4249
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.22621.4249
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion

**Comment by FabienTschanz** [comment] 2024-10-30 09:52
@CovidtheDog2024 Your first issue is resolved by https://github.com/microsoft/Microsoft365DSC/pull/5254 (duplicate of #5246). The second one, as already mentioned a couple of times, happens because you have more than one policy with the display name `test1`. For consistency reasons, you must only have one policy with this name in your environment.

**Comment by FabienTschanz** [comment] 2024-11-04 20:04
Your second issue is probably fixed by #5328. Please check and close the issue if it is solved.

**Comment by CovidtheDog2024** [comment] 2024-11-11 06:32
@FabienTschanz  Thanks you and more power! 
The two issues have been resolved. 

However, there is new issue.:
**DSC version : 1.24.1016.1**
Parameter Name : **onboarding_fromconnector** (This parameter does not present on the previous Version)


**_Error During creating the MOF File:_**

At C:\IntuneEndpointDetectionAndResponsePolicyWindows10\M365TenantConfig.ps1:80 char:13
+             onboarding_fromconnector = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~
The member 'onboarding_fromconnector' is not valid. Valid members are
'AccessTokens', 'ApplicationId', 'ApplicationSecret', 'Assignments', 'CertificateThumbprint', 'ConfigurationBlob', 'ConfigurationType', 'Credential', 'DependsOn', 'Description', 
'DisplayName', 'Ensure', 'Identity', 'ManagedIdentity', 'PsDscRunAsCredential', 'RoleScopeTagIds', 'SampleSharing', 'TenantId'.
At C:\IntuneEndpointDetectionAndResponsePolicyWindows10\M365TenantConfig.ps1:100 char:13
+             onboarding_fromconnector = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~
The member 'onboarding_fromconnector' is not valid. Valid members are
'AccessTokens', 'ApplicationId', 'ApplicationSecret', 'Assignments', 'CertificateThumbprint', 'ConfigurationBlob', 'ConfigurationType', 'Credential', 'DependsOn', 'Description', 
'DisplayName', 'Ensure', 'Identity', 'ManagedIdentity', 'PsDscRunAsCredential', 'RoleScopeTagIds', 'SampleSharing', 'TenantId'.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidInstanceProperty


**Configuration:**
   IntuneEndpointDetectionAndResponsePolicyWindows10 "IntuneEndpointDetectionAndResponsePolicyWindows10-EDR policy"
        {
            Assignments              = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    groupDisplayName = 'TestGroup'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = 'XXXXXXXXXXXXXXXXXXX'
                }
            );
            ConfigurationType        = "autofromconnector";
            Credential               = $Credscredential;
            Description              = "";
            DisplayName              = "EDR policy";
            Ensure                   = "Present";
            Identity                 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            onboarding_fromconnector = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            RoleScopeTagIds          = @("0");
            SampleSharing            = "1";
        }

**Comment by FabienTschanz** [comment] 2024-11-11 07:50
@CovidtheDog2024 Can you please check with version 1.24.1106.3? The version you are using does not include the fixes.

**Comment by CovidtheDog2024** [comment] 2024-11-11 08:34
Hi @FabienTschanz,

Same error using 1.24.1106.3

At C:\IntuneEndpointDetectionAndResponsePolicyWindows10\M365TenantConfig.ps1:80 char:13
+             onboarding_fromconnector = "xxxxxxxxxxxxxxxxxxxxxxxxxxx ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~
The member 'onboarding_fromconnector' is not valid. Valid members are
'AccessTokens', 'ApplicationId', 'ApplicationSecret', 'Assignments', 'CertificateThumbprint', 'ConfigurationBlob', 'ConfigurationType', 'Credential', 'DependsOn', 'Description', 
'DisplayName', 'Ensure', 'Identity', 'ManagedIdentity', 'PsDscRunAsCredential', 'RoleScopeTagIds', 'SampleSharing', 'TenantId'.
At C:\IntuneEndpointDetectionAndResponsePolicyWindows10\M365TenantConfig.ps1:100 char:13
+             onboarding_fromconnector = "xxxxxxxxxxxxxxxxxxxxxxxxx ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~
The member 'onboarding_fromconnector' is not valid. Valid members are
'AccessTokens', 'ApplicationId', 'ApplicationSecret', 'Assignments', 'CertificateThumbprint', 'ConfigurationBlob', 'ConfigurationType', 'Credential', 'DependsOn', 'Description', 
'DisplayName', 'Ensure', 'Identity', 'ManagedIdentity', 'PsDscRunAsCredential', 'RoleScopeTagIds', 'SampleSharing', 'TenantId'.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidInstanceProperty
 

PS C:\IntuneEndpointDetectionAndResponsePolicyWindows10> Get-Module Microsoft365DSC -ListAvailable | Select-Object ModuleBase, Version

ModuleBase                                                             Version    
----------                                                             -------    
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1106.3 1.24.1106.3

**Comment by FabienTschanz** [comment] 2024-11-11 19:31
@CovidtheDog2024 Thank you, I think it's the same issue as #5377. Will update when I have a fix for it, currently installing my SCCM test environment.

**Comment by FabienTschanz** [comment] 2024-11-12 22:07
@CovidtheDog2024 Quick question: Did you do an export of the configuration or was it one that was previously created?

**Comment by CovidtheDog2024** [comment] 2024-11-13 05:56
Hi @FabienTschanz,
Yes, I did export. There is new parameter on version 1.24.1106.1 **onboarding_fromconnector** which is not exported in the previous version.

**Comment by FabienTschanz** [comment] 2024-11-13 12:53
@CovidtheDog2024 PR #5393 will remove this property from the export. It was added by mistake due to changes in the background service used for the source generation because the name changed.

**Closed as completed** 2024-11-13 14:23 UTC

**Comment by CovidtheDog2024** [comment] 2024-11-15 09:35
@FabienTschanz  @NikCharlebois  and @ykuijs 

This is to confirm that the reported error has been resolved. Thank you, and I appreciate your efforts.
