### ISSUE TITLE
AADGroupsSettings export not providing the desired values as documented

### ISSUE THREAD

**Issue by DUeffing** [microsoft/Microsoft365DSC#3333] opened 2023-05-24 08:41 UTC
ISSUE TITLE:
    AADGroupsSettings: the export of the ressource does not included the desired values like "EnableGroupCreation", "AllowGuestsToBeGroupOwner" and so on as outlined within the documentation:

https://microsoft365dsc.com/resources/azure-ad/AADGroupsSettings/

    ISSUE DESCRIPTION (this template):
   When running the following command the content of the created .ps1 file does not contain the desired values:
   Export-M365DSCConfiguration -Components @("AADGroupsSettings") -Credential $Credstenantadmin -Path C:\temp\GroupExport -FileName "groupsetting.ps1"

 
#### Verbose logs showing the problem
no error message or similar is available

#### Suggested solution to the issue
the export should include the values as described in the documentation for the AADGroupsSettings ressource

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Export-M365DSCConfiguration -Components @("AADGroupsSettings") -Credential $Credstenantadmin -Path C:\temp\GroupExport -FileName "groupsetting.ps1"

content of the created .ps1 file:
Generated with Microsoft365DSC version 1.23.517.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration groupsetting
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.23.517.1'

    Node localhost
    {
        AADGroupsSettings "AADGroupsSettings"
        {
            Credential           = $Credscredential;
            Ensure               = "Absent";
            IsSingleInstance     = "Yes";
        }
    }
}

groupsetting -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

ModuleBase                                                            Version   
----------                                                            -------   
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.517.1 1.23.517.1

[groupsetting_export_ps1.txt](https://github.com/microsoft/Microsoft365DSC/files/11552304/groupsetting_export_ps1.txt)

**Comment by andikrueger** [comment] 2023-05-24 19:35
Could you share the output of the following command:

```powershell

Connect-MGGraph

Get-MgDirectorySetting | Where-Object -FilterScript { $_.DisplayName -eq 'Group.Unified' }

```

**Comment by DUeffing** [comment] 2023-05-30 10:12
@andikrueger , did you have any chance to check the information I provided? Thanks

**Comment by NikCharlebois** [comment] 2023-06-02 15:11
This is a first for me (seeing the return of the API be null). Can you confirm you have granted the proper consent in Graph explorer and try again (I see you have a 200 return so it should be a good already, but just checking). Also, what do you get when you go to:
https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupsManagementMenuBlade/~/General

**Comment by DUeffing** [comment] 2023-06-06 12:32
Hi @NikCharlebois, thanks for your feedback. 

I checked the consent and it looks good:
<img width="902" alt="image" src="https://github.com/microsoft/Microsoft365DSC/assets/94981829/5749326c-29e7-4428-8049-6f9906fe30ce">

The link you provided is opening the corresponding group setting blade in the portal. Both are executed with the same account (global admin)

<img width="656" alt="image" src="https://github.com/microsoft/Microsoft365DSC/assets/94981829/203181fe-aec2-45dd-b54e-309aabaa4ca3">

Are you able to get the information on a tenant accessible by you?

**Comment by NikCharlebois** [comment] 2023-06-09 17:46
We are unfortunately not able to reproduce on any of our tenants. Do you have any other tenants accessible to you that you could test it on by any chance?

**Comment by DUeffing** [comment] 2023-06-12 07:47
Hi @NikCharlebois, thanks for your reply. I tested it with two different tenants with the same behavioral.

**Comment by NikCharlebois** [comment] 2023-06-14 14:48
Ok, I think I may be able to replicate. Can you go to you tenant, and under Azure AD > Groups > General toggle a setting and save. Then toggle it back and save, then retry the API.

**Comment by DUeffing** [comment] 2023-06-15 06:41
Hi, I tested it. However the result of the API call is still the same. I tried various ways in changing settings / saving on the groups general tab but the result is still the same.

**Comment by NikCharlebois** [comment] 2023-06-15 18:44
@andikrueger are you able to also try my recommendation to toggle it off and on and see if that also fixes it for you? Thanks

**Comment by andikrueger** [comment] 2023-06-16 08:08
Just fired up graph explorer and there is no auto-complete for /settings:

![image](https://github.com/microsoft/Microsoft365DSC/assets/15608729/a713ebb3-1310-42d7-9fbb-833a4f4293e2)

groupSettings results in an error though:

```json
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'groupSettings'.",
        "innerError": {
            "date": "2023-06-16T08:05:26",
            "request-id": "f0c42db7-43a0-4f47-b771-be07f33d3c26",
            "client-request-id": "540398e0-afe5-832d-4c0d-22c4effa7aff"
        }
    }
}
```

Looks like, there is some change happening. Changing the settings and running a new query for /settings, results still in a null return.

![image](https://github.com/microsoft/Microsoft365DSC/assets/15608729/119eae21-ea4d-4447-b188-4add5cff6b8f)

**Comment by andikrueger** [comment] 2023-06-16 17:30
I did the very same steps and it did not change - presumably a timing issue. Will try to test it next week again.

**Comment by DUeffing** [comment] 2023-06-20 11:19
Hi Nik,

I did the same steps as previously described and were able to reproduce the behavior and the graph query is now showing the details.

An observation I made is, that the two tenants I previously used are in the EU and the new one (where it works) is in the US.

Best regards
Daniel

**Comment by NikCharlebois** [comment] 2023-06-26 19:28
And does the above steps also fix it for EU tenants?

**Comment by DUeffing** [comment] 2023-06-27 06:47
Hi, I created a brand new tenant based in the EU and the described steps fixes the issues accordingly. For an existing / “older” tenant this is not working

**Comment by DUeffing** [comment] 2023-06-27 07:20
while diving deeper in this area, the question came up why the M365DSC just leveraging a few of the provided values from the https://graph.microsoft.com/beta/settings query. The result of the query is the following:

```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#settings",
    "value": [
        {
            "id": "b67bf3a5-48e8-4429-96ed-b8f36106038e",
            "displayName": "Group.Unified",
            "templateId": "62375ab9-6b52-47ed-826b-58e47e0e304b",
            "values": [
                {
                    "name": "NewUnifiedGroupWritebackDefault",
                    "value": "true"
                },
                {
                    "name": "EnableMIPLabels",
                    "value": "false"
                },
                {
                    "name": "CustomBlockedWordsList",
                    "value": ""
                },
                {
                    "name": "EnableMSStandardBlockedWords",
                    "value": "false"
                },
                {
                    "name": "ClassificationDescriptions",
                    "value": ""
                },
                {
                    "name": "DefaultClassification",
                    "value": ""
                },
                {
                    "name": "PrefixSuffixNamingRequirement",
                    "value": ""
                },
                {
                    "name": "AllowGuestsToBeGroupOwner",
                    "value": "false"
                },
                {
                    "name": "AllowGuestsToAccessGroups",
                    "value": "true"
                },
                {
                    "name": "GuestUsageGuidelinesUrl",
                    "value": ""
                },
                {
                    "name": "GroupCreationAllowedGroupId",
                    "value": ""
                },
                {
                    "name": "AllowToAddGuests",
                    "value": "true"
                },
                {
                    "name": "UsageGuidelinesUrl",
                    "value": ""
                },
                {
                    "name": "ClassificationList",
                    "value": ""
                },
                {
                    "name": "EnableGroupCreation",
                    "value": "true"
                }
            ]
        }
    ]
}

```
where the M365DSC export for group setting contains the following values:

```
 AADGroupsSettings "AADGroupsSettings"
        {
            AllowGuestsToAccessGroups = $True;
            AllowGuestsToBeGroupOwner = $False;
            AllowToAddGuests          = $True;
            Credential                = $Credscredential;
            EnableGroupCreation       = $False;
            Ensure                    = "Present";
            GuestUsageGuidelinesUrl   = "";
            IsSingleInstance          = "Yes";
            UsageGuidelinesUrl        = "";
        }
```

**Comment by NikCharlebois** [comment] 2023-06-27 10:45
Some of these properties are handled by other resources. E.g., AADGroupsNamingPolicy

**Comment by NikCharlebois** [comment] 2023-09-11 19:12
Closing

**Closed by NikCharlebois** 2023-09-11 19:12 UTC
Labels: Pending Information, Azure Active Directory, V1.23.517.1
