### ISSUE TITLE
Integrating with Azure DevOps Whitepaper document link not working

### ISSUE THREAD

**Issue by ayuzuf** [microsoft/Microsoft365DSC#4639] opened 2024-05-06 10:35 UTC

**Comment by andikrueger** [comment] 2024-05-06 20:27
Could you please confirm if you can reach this link: https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf

**Comment by ayuzuf** [comment] 2024-05-06 21:09
No I cannot reach it.

[Image.png]

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ayuzuf** [comment] 2024-05-06 21:15
I get “The connection to this website is not safe” error and cannot proceed any further. 

I think it’s SSL issue. 

![image](https://github.com/microsoft/Microsoft365DSC/assets/17231728/f2f8d28c-4503-4198-aad5-2f815fd25698)

**Comment by ayuzuf** [comment] 2024-05-09 12:48
Can this be fixed, or maybe you can share the pdf document?

**Comment by FabienTschanz** [comment] 2024-07-25 20:41
@ayuzuf Is the link still not working for you? Here's the pdf if you still want it: 
[Managing Microsoft 365 with Microsoft365Dsc and Azure DevOps.pdf](https://github.com/user-attachments/files/16383558/Managing.Microsoft.365.with.Microsoft365Dsc.and.Azure.DevOps.pdf)

If the issue is resolved, please close it then. Thank you.

**Comment by ayuzuf** [comment] 2024-07-25 21:26
Resolved! Thank you Fabien

**Closed** 2024-07-25 21:25 UTC
Labels: Pending Information, Documentation, DevOps
