### ISSUE TITLE
Issues with Export-O365Configuration using MFA

### ISSUE THREAD

**Issue by jfrobichaud** [microsoft/Microsoft365DSC#132] opened 2019-07-04 18:28 UTC
Hi, I'm trying to use the Export-O365Configuration command, but my account is using MFA and it is  throwing the following error:

Connect-AzureAD : AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 

Connect-AzureAD : Response status code does not indicate success: 400 (BadRequest).

Thanks

**Comment by NikCharlebois** [comment] 2019-07-04 18:49
Salut @jfrobichaud !

@brianlala that is one for you buddy

**Comment by brianlala** [comment] 2019-07-04 19:26
This is exactly what my recently-merged changes were meant to address... what version of the module are you using @jfrobichaud ?

**Comment by NikCharlebois** [comment] 2019-07-04 19:54
@jfrobichaud the changes that @brianlala is refering to were merged into this GitHub repo this morning. If you install the module from the PowerShell Gallery, you won't get those bits. You will need to grab the latest version from GitHub directly. Let me know if you required further assistance with grabbing the latest bits.

**Comment by jfrobichaud** [comment] 2019-07-05 12:50
Thanks, login successful now.

**Comment by NikCharlebois** [comment] 2019-07-05 12:55
Glad it worked. Will leave open for the day, let me know if you encounter other issues. We are aware of a case where you may get incorrectly prompted for credentials again mid-way through the extraction. We are working on a PR to have this fixed ASAP.

**Comment by wheelerk** [comment] 2019-12-03 18:54
When I provide my creds, the GUI just disappears.  I wonder if this can be updated to support GCC High?  Or a branch for GCC High.

**Comment by NikCharlebois** [comment] 2019-12-03 20:04
@wheelerk in the actually PowerShell console you used to launched the GUI, do you see any verbose output at all? E.g. Extracting O365AdminAuditLogConfig

**Comment by wheelerk** [comment] 2019-12-03 20:38
No, the cursor just continues to flash.  On another note, my GA is MFA enforces.  Oh wait, I’m seeing An error log.

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by wheelerk** [comment] 2019-12-03 20:41
No, the cursor just continues to flash.  On another note, my GA is MFA enforces.  Oh wait, I’m seeing An error log.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by NikCharlebois** [comment] 2019-12-03 20:52
@wheelerk can you paste in the redacted error log's content?

**Comment by wheelerk** [comment] 2019-12-03 20:58
[2019/12/03 03:31:53]
{AuthenticationError}
Microsoft.Open.Azure.AD.CommonLibrary.AadAuthenticationFailedException: One or more errors occurred.: unknown_user_type: Unknown User Type ---> System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: unknown_user_type: Unknown User Type
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenNonInteractiveHandler.<PreTokenRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Open.Azure.AD.CommonLibrary.UserTokenProvider.DoAcquireToken(AdalConfiguration config, PromptBehavior promptBehavior, String userId, SecureString password) in E:\bt\934800\repo\src\dev\PowerShell.V2\CommonLibrary\TokenProvider\UserTokenProvider.cs:line 228
   at Microsoft.Open.Azure.AD.CommonLibrary.UserTokenProvider.SafeAquireToken(AdalConfiguration config, ShowDialog showDialog, String userId, SecureString password, Exception& ex) in E:\bt\934800\repo\src\dev\PowerShell.V2\CommonLibrary\TokenProvider\UserTokenProvider.cs:line 152
   --- End of inner exception stack trace ---
   at Microsoft.Open.Azure.AD.CommonLibrary.UserTokenProvider.AcquireToken(AdalConfiguration config, ShowDialog promptBehavior, String userId, SecureString password) in E:\bt\934800\repo\src\dev\PowerShell.V2\CommonLibrary\TokenProvider\UserTokenProvider.cs:line 134
  at Microsoft.Open.Azure.AD.CommonLibrary.UserTokenProvider.GetAccessToken(AdalConfiguration config, ShowDialog promptBehavior, String userId, SecureString password, AccountType credentialType) in E:\bt\934800\repo\src\dev\PowerShell.V2\CommonLibrary\TokenProvider\UserTokenProvider.cs:line 57
   at Microsoft.Open.Azure.AD.CommonLibrary.AuthenticationFactory.Authenticate(AzureAccount account, AzureEnvironment environment, String tenantId, SecureString password, ShowDialog promptBehavior, TokenCache tokenCache, Endpoint resourceId) in E:\bt\934800\repo\src\dev\PowerShell.V2\CommonLibrary\AuthenticationFactory.cs:line 59
   at Microsoft.Open.Azure.AD.CommonLibrary.RMProfileClient.AcquireAccessToken(AzureAccount account, AzureEnvironment environment, String tenantId, SecureString password, ShowDialog promptBehavior) in E:\bt\934800\repo\src\dev\PowerShell.V2\CommonLibrary\RMProfileClient.cs:line 127
   at Microsoft.Open.Azure.AD.CommonLibrary.RMProfileClient.Login(AzureAccount account, AzureEnvironment environment, String tenantId, SecureString password) in E:\bt\934800\repo\src\dev\PowerShell.V2\CommonLibrary\RMProfileClient.cs:line 55
   at Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD.ProcessRecord() in E:\bt\934800\repo\src\dev\PowerShell.V2\CommonLibrary\ConnectAzureAD.cs:line 163


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NikCharlebois** [comment] 2019-12-04 04:47
@wheelerk find me on twitter, and let me know your email address. I'd like to follow-up offline to get additional info about the account sued to connect. Will take it back to this thread for Knowledge Base once root cause has been identified. My handle is @NikCharlebois

**Comment by wheelerk** [comment] 2020-01-16 13:55
Any chance we can get this working with accounts that use MFA?

**Closed** 2020-06-02 18:33 UTC
Labels: Bug
