### ISSUE TITLE
New-M365DSCReportFromConfiguration: $OrganizationName is not replaced with actual value

### ISSUE THREAD

**Issue by Blubberich** [microsoft/Microsoft365DSC#3007] opened 2023-03-15 12:52 UTC
#### Details of the scenario you tried and the problem that is occurring

First I did
>$Credential = Get-Credential
 
Then made an export of the tenant config with
>Export-M365DSCConfiguration -Components @("AADGroup", "AADUser") -Credential $Credential -ConfigurationName "MBC-Demo" -Path "C:\Temp\" -FileName "MBC-Demo_-_Konfig_AAD.ps1"

Then I created an HTML report with
>New-M365DSCReportFromConfiguration -Type 'HTML' -ConfigurationPath "C:\Temp\MBC-Demo_-_Konfig_AAD.ps1" -OutputPath "C:\Temp\MBC-Demo_-_Report_AAD.html"

I got no errors.

#### Showing the problem

The problem is that $OrganizationName is not replaced in any place in the report, see the image
![image](https://user-images.githubusercontent.com/127954071/225311159-7517599d-32b6-4c00-ae12-968b7736a6a0.png)

#### Suggested solution to the issue

`$OrganizationName` should be replaced as with the correct value.
The `C:\Temp\MBC-Demo_-Konfig_AAD.ps1` file contains `$OrganizationName = $CredsCredential.UserName.Split('@')[1]` but I don't know why that does not work.

### Workaround

Currently I replace in the .ps1 file e. g.
`Owners = @("l.skywalker@$OrganizationName");`
with
`Owners = @("l.skywalker@mbc-demo.de");`
and get what I actually want:
![image](https://user-images.githubusercontent.com/127954071/225314189-4f100287-a0f2-499e-87db-46e09e6ee413.png)

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Version: 1.23.308.1

**Comment by andikrueger** [comment] 2023-03-15 13:04
This is by design. During the export we replace all information that would bind the configuration to one tenant. This enables us to export one tenant and import the very same configuration into another tenant. 

Please have a look at #2609 I think this issue holds valuable information.

**Comment by andikrueger** [comment] 2023-03-15 14:48
Closing this in favor of #2609

**Closed by andikrueger** 2023-03-15 14:48 UTC
Labels: Enhancement, Pending Information, Core Engine
