### ISSUE TITLE
Error with "Test TargetResource" does not run. Error message: "The response content cannot be parsed because the Internet Explorer module is not available, or the configuration is displayed the first time you start Internet explorer. Apply -usebasicparsing and try again."

### ISSUE THREAD

**Issue by ahohenschuh** [microsoft/Microsoft365DSC#637] opened 2020-06-10 10:19 UTC

**Comment by mdcaddic** [comment] 2020-06-11 04:30
Yeah I had that yesterday too. I created a local gpo using this.
https://wahlnetwork.com/2015/11/17/solving-the-first-launch-configuration-error-with-powershells-invoke-webrequest-cmdlet/

**Comment by sfr23** [comment] 2020-06-16 10:42
Hi @ahohenschuh ,
a workaround is to disable IE First Run for System Account.
For Scripts on non-Domain Machines you can set this Registry Key:

```
$IEFirstRunRegPath = "HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main"
$IEFirstRunValueName = "DisableFirstRunCustomize"
$IEFirstRunValue = 1
new-item -Path $IEFirstRunRegPath -force | Out-Null
New-ItemProperty -Path $IEFirstRunRegPath -Name $IEFirstRunValueName -Value $IEFirstRunValue -PropertyType DWORD -Force | Out-Null
```

**Comment by NikCharlebois** [comment] 2020-06-18 20:14
Thanks folks. closing the issue since we have a fix.

**Closed by NikCharlebois** 2020-06-18 20:14 UTC
Labels: Bug

**Comment by BriskWinter** [comment] 2020-08-17 19:21
Is there no other way around this? Error will prevent adoption since many systems running this will not have internet explorer ran previously.

**Comment by NikCharlebois** [comment] 2020-11-20 21:17
Just confirmed with a client that installing .NET 4.8:
https://dotnet.microsoft.com/download/dotnet-framework/net48

Will fix the issue. Only the runtime is required

**Comment by KenBenjamin** [comment] 2021-02-22 20:07
Had to reboot the VM afterwards to get this fix to run. I added it into my prep.ps1 since it's required.

**Comment by hmank** [comment] 2021-02-24 16:25
I don't have a VM, i'm running my scripts in an Azure Run Book.

**Comment by ykuijs** [comment] 2021-02-24 16:29
I created an issue for MSCloudLoginAssistant this morning: microsoft/MSCloudLoginAssistant#102

I haven't tested this yet, but I suspect fixing that issue will fix this issue as well.
