### ISSUE TITLE
IntuneAntivirusPolicyWindows10SettingCatalog: Cannot export on mshosted pipelines

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#3311] opened 2023-05-15 14:26 UTC
#### Details of the scenario you tried and the problem that is occurring

While exporting the whole Intune workload using Export-M365DSCConfiguration, on mshosted pipelines instead of self-hosted VM, the very first resource IntuneAntivirusPolicyWindows10SettingCatalog cannot be exported, at least with certificate-based authentication, even if there are no policies of this type in the tenant but all other resources are exported without issues.

After changing my code to show the event logs it seems that cmdlet Get-MgDeviceManagementConfigurationPolicy is not recognized, see log below, this is because it's only available in Graph's beta profile, nevertheless other resources later on use the very same cmdlet and are exported without issues.

Note that while using self-hosted VM I cannot replicate this issue, then on mshosted pipelines on DevOps results in the same failure all the time and just for this specific resource which happens to be the first to be exported from Intune workload, most likely it can be reproduced with local clean containers such as the ones used on mshosted pipelines (can't verify this ATM).

At the moment my workaround for having this working is to call code below after installing M365Dsc module and just right before calling Export-M365DSCConfiguration, but of course this is not a final solution. I also already tried to make a copy of IntuneAntivirusPolicyWindows10SettingCatalog.psm1 to my repo, remove parameter `SkipModuleReload' from cmdlet M365DSCConnection on method Export, copy the new file to where M365Dsc is installed but it still fails. Any clues on what might be causing this issue?

```powershell
[...]
Get-Module -ListAvailable -Name "Microsoft.Graph.DeviceManagement*" | %{
    Import-Module $_ -Force
}
[...]
```
#### Verbose logs showing the problem

[2023-05-15 11:42:14] - Error during Export:

{ The term 'Get-MgDeviceManagementConfigurationPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. } \ at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.510.1\DSCResources\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog.psm1: line 1390
 \ at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.510.1\modules\M365DSCReverse.psm1: line 619
 \ at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.510.1\modules\M365DSCUtil.psm1: line 1268
 \ at <ScriptBlock>, D:\a\1\s\Source\Scripts\Exporter.ps1: line 63
 \ at <ScriptBlock>, D:\a\_temp\e9d05e6e-5935-4e23-9956-a292ad63bd45.ps1: line 4
 \ at <ScriptBlock>, <No file>: line 1

TenantId: REDACTED

#### Suggested solution to the issue

N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

N/A

#### The operating system the target node is running

Win10

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.23.510.1

**Comment by andikrueger** [comment] 2023-05-15 14:30
Did you try to export only IntuneAntivirusPolicyWindows10SettingCatalog in a call? would be interesting if this is different.

**Comment by ricmestre** [comment] 2023-05-15 14:50
Nope, still fails even if it's the only component being exported.

[1/1] Extracting [IntuneAntivirusPolicyWindows10SettingCatalog] using {CertificateThumbprint}...❌

**Comment by William-Francillette** [comment] 2023-05-16 07:55
Interesting -
Can you check which version of microsoft.graph.devicemanagement you are running please
Also could you try exporting IntuneSettingCatalogCustomPolicyWindows10, the resource use Get-MgDeviceManagementConfigurationPolicy as well

**Comment by ricmestre** [comment] 2023-05-16 08:26
@William-Francillette I'm not doing anything out of the ordinary, I get to install M365Dsc, its dependencies through Update-M365DSCDependencies and then call the export, so the version of the modules that get installed are pinned in the Manifest.psd1. I'm now trying instead to just export IntuneSettingCatalogCustomPolicyWindows10, will let you know once it's finished.

**Comment by ricmestre** [comment] 2023-05-16 08:51
Also failed, but it seems that the containers come with Microsoft.Graph.* already pre-installed (and pre-loaded into the PS session) but it happens to be the same version 1.27.0 so with Update-M365DSCDependencies they get overwritten, I'd understand they needed to be reloaded if the version differed... Anyway now I'm trying again but calling Remove-Module on all Graph modules before proceeding, let me check.

**Comment by ricmestre** [comment] 2023-05-16 10:50
Nope, it's just not possible, even after removing the Graph modules AND deleting them (then proceed with M365Dsc installation and its dependencies) it still complains about the same issue as if the modules are still somehow lingering around, the only way to make it work for modules using Beta cmdlets is to reimport the corresponding modules from where those cmdlets are being loaded. Not only that it only works if I do that directly from the script where I'm doing the export, if I reimport the modules from another custom module I have even though they are reimported it also fails to export!!

Any clues on this? Or do I have to carry this botched workaround?

**Comment by William-Francillette** [comment] 2023-05-16 10:57
Have you tried to explicitly install Microsoft.Graph.DeviceManagement?
`install-module Microsoft.Graph.DeviceManagement -force`

**Comment by andikrueger** [comment] 2023-05-16 11:09
Could you test if this issue still occurs if you manually connect to ms graph:

connect-M365Tenant -Workload MicrosoftGraph -Profile Beta 

prior to running the export?

**Comment by ricmestre** [comment] 2023-05-16 12:55
@andikrueger It didn't make a difference, issue is still there. Now I also tested 3 resources, 1 with v1.0 profile and 2 in beta, and this time it failed on both calling the beta profile so it seems that when calling the whole Intune workload even if it fails for the first resource (because it uses beta) eventually it "heals" itself somewhere down the road.

@William-Francillette That is what I already do through Update-M365DSCDependencies, the only difference being that this one calls it with a specific RequiredVersion.

**Comment by andikrueger** [comment] 2023-05-16 13:06
The change of the profile happens within MSCloudLoginAssistant: 

https://github.com/microsoft/MSCloudLoginAssistant/blob/4989f9185d847b3762d90b6d19357604d7d3a7f6/Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1#L14-L25

Could you try to run something like this with MSCloudLoginAssistant and see, if the issue is persistant:

```powershell

Connect-M365Tenant -Workload MicrosoftGraph -ProfileName Beta

# Call to a Graph Beta Endpoint

Connect-M365Tenant -Workload MicrosoftGraph -ProfileName V1.0

# Call to a Graph V1 Endpoint

Connect-M365Tenant -Workload MicrosoftGraph -ProfileName Beta

# Call to a Graph Beta Endpoint

Connect-M365Tenant -Workload MicrosoftGraph

# Call to a Graph V1 Endpoint

Connect-M365Tenant -Workload MicrosoftGraph -ProfileName Beta

# Call to a Graph Beta Endpoint

```

**Comment by ricmestre** [comment] 2023-05-16 13:24
It's currently installing the dependencies, but this is the code I'm gonna test in the pipeline by calling it 6 times in a row.

```powershell
Connect-M365Tenant -Workload $Workload `
    -ApplicationId $ApplicationId `
    -TenantId $ProdTenantId `
    -CertificateThumbprint $CertThumbprint `
    -ProfileName "Beta"
Get-MgDeviceManagementConfigurationPolicy -All

Connect-M365Tenant -Workload $Workload `
    -ApplicationId $ApplicationId `
    -TenantId $ProdTenantId `
    -CertificateThumbprint $CertThumbprint `
    -ProfileName "v1.0"
Get-MgGroup -All
```

**Comment by ricmestre** [comment] 2023-05-16 14:46
With Microsoft.Graph.Intune now installed when calling Connect-M365Tenant it's assuming I'm using app secret and fails with the below but it's clear that I'm using cert thumbprint.

```powershell
Connect-MSGraph : Value cannot be null.
Parameter name: clientSecret
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.110\Workloads\Intune.psm1:71 char:13
+             Connect-MSGraph -ClientSecret $Global:MSCloudLoginConnect ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MSGraph], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Connect
```

**Comment by andikrueger** [comment] 2023-05-16 16:05
Thanks for all the tests so far. Actually, I thought Intune would use MSGraph - Which is does not:

https://github.com/microsoft/MSCloudLoginAssistant/blob/Dev/Modules/MSCloudLoginAssistant/Workloads/Intune.psm1

It calls Connect-MGGraph and changes some environment enpoint, but does not properly handle the change to Beta profile nor other authentication methods. This issue needs to be fixed within MSCloudLoginAssistant.

**Comment by ricmestre** [comment] 2023-05-16 16:31
From my point of view shouldn't the Intune workload at this point just be an alias to MicrosoftGraph? That way it wouldn't be reaching that code in MSCloudLoginAssistant and failing this way as @William-Francillette also already reported before.

**Comment by andikrueger** [comment] 2023-05-16 16:44
The Intune workload within MSCloudLoginAssistant is a year old. 

@William-Francillette what Workload are you currently using in the other Intune resources? Intune or MicrosoftGraph?

**Comment by William-Francillette** [comment] 2023-05-16 16:45
Graph

**Comment by andikrueger** [comment] 2023-05-16 16:48
Is there any reason why we use the Intune workload of MSCloudLoginAssistant at all?

**Comment by William-Francillette** [comment] 2023-05-16 16:49
It's probably legacy as the whole Intune portal is using the MS Graph now

**Comment by ricmestre** [comment] 2023-05-16 16:58
The resources themselves call New-M365DSCConnection with workload MicrosoftGraph, but Export-M365DSCConfiguration, and by extent Start-M365DSCConfigurationExtract, actually use workload Intune so at line 513 of M365DSCReverse.psm1 as per below it will say that it's connecting to Intune and that's what's gonna be used in Connect-M365Tenant.

```powershell
foreach ($Workload in $WorkloadsToConnectTo)
        {
            Write-Host "Connecting to {$Workload}..." -NoNewline
            $ConnectionParams = @{
                Workload              = $Workload
                ApplicationId         = $ApplicationId
                ApplicationSecret     = $ApplicationSecret
                TenantId              = $TenantId
                CertificateThumbprint = $CertificateThumbprint
                CertificatePath       = $CertificatePath
                CertificatePassword   = $CertificatePassword.Password
                Credential            = $Credential
                Identity              = $ManagedIdentity.IsPresent
            }

            try
            {
                Connect-M365Tenant @ConnectionParams | Out-Null
                Write-Host $Global:M365DSCEmojiGreenCheckmark
            }
            catch
            {
                Write-Host $Global:M365DSCEmojiRedX
                throw $_
            }
        }
```

**Comment by andikrueger** [comment] 2023-05-16 16:58
From this perspective, it would make sense to change all resources to use MicrosoftGraph instead of the Intune workload.

**Comment by ricmestre** [comment] 2023-06-09 12:48
Any updates on this one?

**Comment by NikCharlebois** [comment] 2023-06-15 19:27
> The resources themselves call New-M365DSCConnection with workload MicrosoftGraph, but Export-M365DSCConfiguration, and by extent Start-M365DSCConfigurationExtract, actually use workload Intune so at line 513 of M365DSCReverse.psm1 as per below it will say that it's connecting to Intune and that's what's gonna be used in Connect-M365Tenant.
> 
> ```powershell
> foreach ($Workload in $WorkloadsToConnectTo)
>         {
>             Write-Host "Connecting to {$Workload}..." -NoNewline
>             $ConnectionParams = @{
>                 Workload              = $Workload
>                 ApplicationId         = $ApplicationId
>                 ApplicationSecret     = $ApplicationSecret
>                 TenantId              = $TenantId
>                 CertificateThumbprint = $CertificateThumbprint
>                 CertificatePath       = $CertificatePath
>                 CertificatePassword   = $CertificatePassword.Password
>                 Credential            = $Credential
>                 Identity              = $ManagedIdentity.IsPresent
>             }
> 
>             try
>             {
>                 Connect-M365Tenant @ConnectionParams | Out-Null
>                 Write-Host $Global:M365DSCEmojiGreenCheckmark
>             }
>             catch
>             {
>                 Write-Host $Global:M365DSCEmojiRedX
>                 throw $_
>             }
>         }
> ```

I don't think it does call into Intu at all. It only calls into the workloads that are returned by the Get-M365DSCWorkloadsListFromResourceNames cmdlet which will never return Intune. It will return MicrosoftGraph instead. The Intune workload in MSCloudLoginAssistant is indeed legacy and we stopped using it back in November of 2021 in favor of MicrosoftGraph.

**Comment by NikCharlebois** [comment] 2023-06-15 19:32
Apologies for being late to the party on this one. Are you saying you are only getting the error when trying to export from a pipeline or are you also getting the same error while running it locally?
![image](https://github.com/microsoft/Microsoft365DSC/assets/2547149/1112ed9f-8502-4514-9ca0-e2442c4b6fc4)

**Comment by ricmestre** [comment] 2023-06-15 19:42
I won't.be able to test with new version until tomorrow but locally it worked, the failure happens while running the pipeline on mshosted, not self-hosted. This happens if the resources reach the Graph Beta endpoint.

As of right now I have a workaround which is to force reimport Microsoft.Graph.DeviceManagement before calling the export but that feels like an hack.

**Comment by William-Francillette** [comment] 2023-06-15 20:05
@ricmestre what do you mean exactly by mshosted pipeline so that we can reproduce the issue?

**Comment by NikCharlebois** [comment] 2023-06-15 20:09
I believe this refers to Hosted Azure Agents instead of having your own dedicated DevOPS agent like we are recommending in the whitepaper. @ricmestre I've seen cases before where modules weren't properly loaded in a session where they had just got installed. Is the workaround you have in place right now problematic for you? What I mean is can you folks live with having to implicitly load the modules like you are doing? I understand it is a strange behavior but if we have a workaround in place, I am wondering how much effort we want to put into troubleshooting this further. Thanks

**Comment by ricmestre** [comment] 2023-06-15 20:09
I'm running this on DevOps, you can select to run your pipelines either on self managed VMs that you control or so called mshosted VMs which are basically Windows Docker containers that are already setup for you.

**Comment by ricmestre** [comment] 2023-06-15 20:20
Honestly since I've a workaround and it's simple enough then it's not too problematic right now, only weird. I guess we can live with it for now, and this can be closed and be looked at a later stage, I'd rather have the PR on ReverseDSC looked at to be honest 😃

**Closed** 2023-06-16 17:08 UTC
Labels: Bug, Pending Information, Intune, Authentication
